#!/bin/bash

echo "=== 昆虫图鉴小程序云函数部署指南 ==="
echo "【重要】目前遇到 'FunctionName parameter could not be found' 错误，这表示云函数未正确部署。"
echo ""
echo "需要部署的云函数列表（共15个）："
echo "管理功能云函数（9个）："
echo "1. getFunFactsList - 获取冷知识列表"
echo "2. getUserList - 获取用户列表"
echo "3. getInsectList - 获取昆虫列表"
echo "4. getBadgeList - 获取勋章列表"
echo "5. saveFunFact - 保存冷知识"
echo "6. deleteFunFact - 删除冷知识"
echo "7. saveBadge - 保存勋章"
echo "8. deleteBadge - 删除勋章"
echo "9. checkAdminPermission - 检查管理员权限"
echo ""
echo "基础功能云函数（6个）："
echo "10. getOpenId - 获取用户OpenID"
echo "11. markFound - 标记昆虫发现"
echo "12. getInsectDetail - 获取昆虫详情"
echo "13. getInsectImages - 获取昆虫图片"
echo "14. baiduImageSearch - 百度图片搜索"
echo "15. updateInsectImage - 更新昆虫图片"
echo ""
echo "详细部署步骤："
echo "1. 打开微信开发者工具，确保项目已打开"
echo "2. 点击左侧导航栏的「云开发」按钮"
echo "3. 在云开发控制台中，选择「云函数」标签"
echo "4. 对于每个云函数："
echo "   a. 点击「上传并部署」-> 「云端安装依赖」（推荐）"
echo "   b. 确保部署到正确的环境ID：cloud1-8ggzed032ed5e7ec"
echo "   c. 等待部署完成并确认状态为「已部署」"
echo ""
echo "问题排查步骤："
echo "1. 检查云函数名称：确保调用的函数名与部署的函数名完全一致"
echo "2. 检查环境ID：确认小程序app.js中的env与云开发控制台中的环境ID一致"
echo "3. 检查云函数状态：在云开发控制台中确认所有函数都显示为「已部署」"
echo "4. 检查权限配置：确认云函数有正确的数据库访问权限"
echo ""
echo "验证部署：部署完成后，可以在云开发控制台使用「测试」功能验证每个函数是否正常工作"
echo "重新编译小程序并测试所有管理功能，确保错误已解决。"